### create a new user

POST http://localhost:3000/api/auth/
Content-Type: application/json

{
    "email": "unmail.com",
    "password": "123456",
    "photo": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.ist",
    "role": 2,
    "online": "true"

}