
@baseUrl=http://localhost:3000
@resource=api
@endpoint=cities
@id=64f90a6c79db44ae99f3a621
@limit=4
@page=1
@name=cities
@sort=asc

### Read All
# Content-Type: application/json
GET {{baseUrl}}/{{resource}}/{{endpoint}}
Content-Type: application/json


### Read Pagination
GET {{baseUrl}}/{{resource}}/{{endpoint}}?limit={{limit}}&page={{page}}&name={{name}}

### Create
POST {{baseUrl}}/{{resource}}/{{endpoint}}
Content-Type: application/json

{
    "name": "Rosario",
    "country": "Argentina",
    "image": "htt-url",
    "_itineraries" : "64fcc0bcadbe9ad61121613a"
}

###
POST {{baseUrl}}/{{resource}}/{{endpoint}}
Content-Type: application/json

     {
       "city": "https://unsplash.com/es/fotos/q7ZlbWbDnYo",
        "price": 77,
        "duration": 3,
        "likes":44,
     }   

### Delete
DELETE {{baseUrl}}/{{resource}}/{{endpoint}}/{{id}}
Content-Type: application/json


### Create
POST {{baseUrl}}/{{resource}}/{{endpoint}}
Content-Type: application/json

{
    "image": "city2",
    "price": 6,
    "duration": 6,
    "likes": 3,
    "_city": "64fcbf65adbe9ad611216135"
}